-- Create topup_orders table
CREATE TABLE IF NOT EXISTS topup_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id VARCHAR(100) NOT NULL UNIQUE,
  user_id INT NOT NULL,
  game_id INT NOT NULL,
  player_id VARCHAR(255) NOT NULL,
  server_id VARCHAR(255) NULL,
  product_id INT NULL,
  amount DECIMAL(15, 2) NOT NULL,
  payment_method VARCHAR(50) DEFAULT 'transfer',
  payment_method_id INT NULL,
  voucher_code VARCHAR(50) NULL,
  payment_proof LONGTEXT NULL,
  payment_expires_at TIMESTAMP NULL,
  status ENUM('pending', 'processing', 'completed', 'failed', 'cancelled') DEFAULT 'pending',
  notes TEXT NULL,
  verified_by INT NULL,
  verified_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  INDEX idx_user (user_id),
  INDEX idx_game (game_id),
  INDEX idx_status (status),
  INDEX idx_order_id (order_id),
  INDEX idx_created_at (created_at),
  INDEX idx_payment_proof (payment_proof),
  INDEX idx_verified_by (verified_by),
  INDEX idx_completed_at (completed_at)
);

